export const TOBACCO_DI_TOKENS = {
    TOBACCO_REPOSITORY: Symbol('TOBACCO_REPOSITORY'),
    TOBACCO_SERVICE: Symbol('TOBACCO_SERVICE'),
    RECOMMEND_TOBACCO_FACADE: Symbol('RECOMMEND_TOBACCO_FACADE'),
} as const;